---
## "Prediction model for CO2 Emissions based on waste and recycling habits"


---
### Executive summary

The app here developed allows you to easily **calculate the CO2 emissions equivalent from waste production** per year, at the net of recycling habits. This is based on a part of the EPA model for calculation of individual emissions.   

  
### Inputs  

- **Number of people (household)**: enter the number of people in the household, which is a base for the estimation of emissions. 
 
- **Which items or products are usually recycled**: check the boxes corresponding to what is usually being recycled in the household. 

### Model 

The model apply an average coefficient of C02 emission per year pro capite.
This is reduced by a coefficient for each of the products recycled.  

### Notes  
Average lbs CO2 equivalent generated from waste per person per year	692	lbs CO2e/year/person from waste. 
Based on *EPA's Inventory of U.S. Greenhouse Gas Emissions and Sinks 1990-2011*,Chapter 8 (Waste), Table 8-3 and Chapter 3, Table 3-1, and *EPA's annual Municipal Solid Waste Characterization Report: Facts and Figures, 2011.*  
  For more details see:  
    http://www3.epa.gov/climatechange/ghgemissions/individual.html  
    https://github.com/0000m0000/co2app  
